### ISSUE TITLE
check os fail on fedora 28

### ISSUE THREAD

**Issue by opentux** [snwh/fedora-post-install#5]
hi, thanks with the script
after run 
sudo ./fedora-post-install.sh

-- Fedora Post-Install Script
-- Starting 'check_os' function
-- Checking which OS you are using...
-- Current OS is: Linux
-- You are using 'Linux'. :D
-- \aCan't check which distribution you are using! Aborting.
--  Aborting...
[opentux@zenbook fedora-post-install]$

**Comment by snwh** [comment]
I think I've fixed this, it was relying on `lsb_release` which isn't installed by default on Fedora, I have changed it to a new method
